general {
  ignore_dbus_inhibit = false
}

listener {
  timeout = 1000
  on-timeout = hyprlock
}

listener {
  timeout = 2000
  on-timeout = systemctl suspend
  on-resume  = sleep 1 && hyprctl dispatch dpms on
}
