#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    # -1.0 - 1.0, 0 means no modification.
    sensitivity = 0

    # Keyboard repeat settings
    repeat_rate = 25
    repeat_delay = 600

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
# gestures {
# 	workspace_swipe = on
# 	workspace_swipe_fingers = 3
# 	workspace_swipe_distance = 300
# 	workspace_swipe_invert = false
# }

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
# Uncomment and adjust device name for your new machine. Check with: hyprctl devices
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }
